check more times for shared secret change in test
in case the agent can still fix it. by checking more the
integration tests have a bigger change of still passing if this
situation occurs on slower machines.

```
RuntimeError: Failed to run raptiformica command on remote host
Warning: Permanently added '172.17.0.4' (ECDSA) to the list of known hosts.
Traceback (most recent call last):
  File "/usr/etc/raptiformica/raptiformica/actions/mesh.py", line 690, in restart_consul_agent_if_necessary
    raise_if_shared_secret_changed()
  File "/usr/etc/raptiformica/raptiformica/utils.py", line 149, in retry_wrapper
    return func(*args, **kwargs)
  File "/usr/etc/raptiformica/raptiformica/actions/mesh.py", line 650, in raise_if_shared_secret_changed
    "The consul shared might have become stale"
raptiformica.actions.mesh.ConsulSharedSecretChanged: The consul shared might have become stale
```